Step2 2
Sergei-Nerobeev/toyota pull request #4
Opened 2024-03-29 15:08 UTC by Sergei-Nerobeev

Merging Step2_2 to Version2

2024-04-04 10:36 UTC, danikirillov requested changes
Осталось совсем чуть-чуть:)

2024-04-04 10:36 UTC, danikirillov commented on src/hu/nero/toyota/detail/Fridge.java
> +    private CountryOfProduction countryOfProduction;
no setter or constructor for this variable

2024-04-04 10:36 UTC, danikirillov commented on src/hu/nero/toyota/detail/Roof.java
> +    private Roof roof;
why do you need a roof inside a roof?

2024-04-04 10:36 UTC, danikirillov commented on src/hu/nero/toyota/detail/Roof.java
> +
setOn(true)?

2024-04-04 10:36 UTC, danikirillov commented on src/hu/nero/toyota/detail/Wheel.java
> +  private CountryOfProduction countryOfProduction;
no setter or controller for this variable

2024-04-04 10:36 UTC, danikirillov commented on src/hu/nero/toyota/factory/CarFactory.java
> +                detailFactory.createRoof().getRoof(),
createRoof is enough, you don't need to use getter here

2024-04-04 10:36 UTC, danikirillov commented on src/hu/nero/toyota/factory/DetailFactory.java
> +        return new Engine(CountryOfProduction.CHINA);
Is it only Chinese factory?

2024-04-04 10:36 UTC, danikirillov commented on src/hu/nero/toyota/factory/DetailFactory.java
> +        Usb usb = new Usb();
where is a country of production?

2024-04-04 10:36 UTC, danikirillov commented on src/hu/nero/toyota/factory/DetailFactory.java
> +        Fridge fridge = new Fridge();
where is a country of production?

2024-04-04 10:36 UTC, danikirillov commented on src/hu/nero/toyota/type/AbstractCar.java
> -    protected Country countryAssembly;
I thought every car should have it's production country. Why did you remove it?

2024-04-05 08:22 UTC, Sergei-Nerobeev commented on src/hu/nero/toyota/detail/Fridge.java
> +    private CountryOfProduction countryOfProduction;
Fixed

2024-04-05 08:24 UTC, Sergei-Nerobeev commented on src/hu/nero/toyota/detail/Roof.java
> +    private Roof roof;
Fixed

2024-04-05 08:29 UTC, Sergei-Nerobeev commented on src/hu/nero/toyota/detail/Roof.java
> +
Fixed. Sad but true(c) ;)

2024-04-05 08:31 UTC, Sergei-Nerobeev commented on src/hu/nero/toyota/factory/CarFactory.java
> +                detailFactory.createRoof().getRoof(),
Fixed

2024-04-05 09:48 UTC, Sergei-Nerobeev commented on src/hu/nero/toyota/factory/DetailFactory.java
> +        return new Engine(CountryOfProduction.CHINA);
Fixed!

2024-04-05 09:50 UTC, Sergei-Nerobeev commented on src/hu/nero/toyota/factory/DetailFactory.java
> +        Usb usb = new Usb();
Fixed

2024-04-05 09:50 UTC, Sergei-Nerobeev commented on src/hu/nero/toyota/factory/DetailFactory.java
> +        Fridge fridge = new Fridge();
Fixed

2024-04-05 09:55 UTC, Sergei-Nerobeev commented on src/hu/nero/toyota/type/AbstractCar.java
> -    protected Country countryAssembly;
Fixed!

2024-04-05 18:04 UTC, danikirillov requested changes

2024-04-05 18:04 UTC, danikirillov commented on src/hu/nero/toyota/detail/WheelRadius.java
> +    SIXTEEN,SEVENTEEN,TWENTY
тебе все еще не нужен енум для чисел. Семнадцать можно написать как 17 и не добавлять сложности в код

2024-04-05 18:04 UTC, danikirillov commented on src/hu/nero/toyota/factory/CarFactory.java
> +                new Wheel(WheelRadius.TWENTY),
почему не используешь фабричный метод?

2024-04-05 18:04 UTC, danikirillov commented on src/hu/nero/toyota/factory/CarFactory.java
> +                CountryOfProduction.CHINA,
машины делаются только в Китае? почему не используешь поле, определяющее страну производства для этой фабрики?

2024-04-07 20:40 UTC, Sergei-Nerobeev commented on src/hu/nero/toyota/detail/Roof.java
> +
Fixed.

2024-04-09 16:49 UTC, danikirillov commented on src/hu/nero/toyota/detail/WheelRadius.java
> +    SIXTEEN,SEVENTEEN,TWENTY
e.g. CAMRY_RADIUS = 16;

2024-04-09 16:51 UTC, danikirillov commented on src/hu/nero/toyota/factory/CarFactory.java
> +                new Wheel(WheelRadius.TWENTY),
detailsFactory.createWheel(20);

2024-04-09 16:53 UTC, danikirillov commented on src/hu/nero/toyota/factory/CarFactory.java
> +                CountryOfProduction.CHINA,
countryOfProduction

2024-04-09 20:36 UTC, Sergei-Nerobeev commented on src/hu/nero/toyota/factory/CarFactory.java
> +                CountryOfProduction.CHINA,
Fixed

2024-04-09 20:54 UTC, Sergei-Nerobeev commented on src/hu/nero/toyota/factory/CarFactory.java
> +                new Wheel(WheelRadius.TWENTY),
Fixed!

2024-04-10 15:33 UTC, closed without merging